version: "3.9"

networks:
  webnet:
    driver: bridge

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certificates:/etc/letsencrypt
    depends_on:
      - module1-server
      - module2-server
      - module3-server
    networks:
      - webnet

  
  module1-server-1:
    image: httpd:latest
    container_name: module1-server-1
    restart: always
    volumes:
      - ./example-module1:/usr/local/apache2/htdocs/
    networks:
      - webnet

  module1-server-2:
    image: httpd:latest
    container_name: module1-server-2
    restart: always
    volumes:
      - ./example-module1:/usr/local/apache2/htdocs/
    networks:
      - webnet


  module2-server-1:
    image: httpd:latest
    container_name: module2-server-1
    restart: always
    volumes:
      - ./example-module2:/usr/local/apache2/htdocs/
    networks:
      - webnet

  module2-server-2:
    image: httpd:latest
    container_name: module2-server-2
    restart: always
    volumes:
      - ./example-module2:/usr/local/apache2/htdocs/
    networks:
      - webnet

 
  module3-server-1:
    image: httpd:latest
    container_name: module3-server-1
    restart: always
    volumes:
      - ./example-module3:/usr/local/apache2/htdocs/
    networks:
      - webnet

  module3-server-2:
    image: httpd:latest
    container_name: module3-server-2
    restart: always
    volumes:
      - ./example-module3:/usr/local/apache2/htdocs/
    networks:
      - webnet
