version: "3.9"

networks:
  webnet:
    driver: bridge

services:
  # Nginx Proxy Din√¢mico 
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certificates:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webnet
    depends_on:
      - module1-server
      - module2-server
      - module3-server

  ########################################
  # Module 1 Backend
  ########################################
  module1-server:
    image: httpd:latest
    restart: always
    volumes:
      - ./example-module1:/usr/local/apache2/htdocs/
    networks:
      - webnet
    environment:
      - VIRTUAL_HOST=module1.main-domain-example.online
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

  ########################################
  # Module 2 Backend
  ########################################
  module2-server:
    image: httpd:latest
    restart: always
    volumes:
      - ./example-module2:/usr/local/apache2/htdocs/
    networks:
      - webnet
    environment:
      - VIRTUAL_HOST=module2.main-domain-example.online
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

  ########################################
  # Module 3 Backend
  ########################################
  module3-server:
    image: httpd:latest
    restart: always
    volumes:
      - ./example-module3:/usr/local/apache2/htdocs/
    networks:
      - webnet
    environment:
      - VIRTUAL_HOST=module3.main-domain-example.online
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
